services:
  mailpit:
    image: axllent/mailpit:latest
    container_name: mailpit
    restart: unless-stopped
    ports:
      - "8025:8025"
      - "1025:1025"
    networks:
      - insurahub-network
    healthcheck:
      test: [ "CMD", "wget", "--spider", "-q", "http://localhost:8025/" ]
      interval: 5s
      timeout: 3s
      retries: 5

  app:
    environment:
      MAIL_HOST: mailpit
      MAIL_PORT: 1025
      MAIL_USERNAME:
      MAIL_PASSWORD:
      MAIL_SENDER: ${MAIL_SENDER}
    depends_on:
      mailpit:
        condition: service_healthy
