CREATE SCHEMA IF NOT EXISTS insurahub AUTHORIZATION CURRENT_USER;

GRANT ALL PRIVILEGES ON SCHEMA insurahub TO CURRENT_USER;

ALTER DEFAULT PRIVILEGES IN SCHEMA insurahub
GRANT ALL ON TABLES TO CURRENT_USER;

ALTER DEFAULT PRIVILEGES IN SCHEMA insurahub
GRANT ALL ON SEQUENCES TO CURRENT_USER;