spring:
  application:
    name: InsuraHub

  h2:
    console:
      enabled: false
      path: /h2-console

  datasource:
    url: ${DATABASE_URL}
    driver-class-name: org.postgresql.Driver
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: validate

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${AUTH0_ISSUER_URI}
          audiences:
            - ${AUTH0_AUDIENCE}

auth0:
  domain: ${AUTH0_DOMAIN}
  client-id: ${AUTH0_M2M_CLIENT_ID}
  client-secret: ${AUTH0_M2M_CLIENT_SECRET}
  connection-name: ${AUTH0_CONNECTION_NAME}

  role:
    consumer: ${AUTH0_CONSUMER_ROLE}
    admin: ${AUTH0_ADMIN_ROLE}

logging:
  level:
    com.cspot:
      DEBUG