spring:
  application:
    name: InsuraHub

  datasource:
    url: ${DATABASE_URL}
    driver-class-name: org.postgresql.Driver
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: validate

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${AUTH0_ISSUER_URI}
          jwk-set-uri: ${AUTH0_JWK_SET_URI}
          audiences:
            - ${AUTH0_AUDIENCE}

  mvc:
    servlet:
      path:
        /api/v1

auth0:
  domain: ${AUTH0_DOMAIN}
  client-id: ${AUTH0_M2M_CLIENT_ID}
  client-secret: ${AUTH0_M2M_CLIENT_SECRET}
  connection-name: ${AUTH0_CONNECTION_NAME}

  role:
    consumer: ${AUTH0_CONSUMER_ROLE}
    admin: ${AUTH0_ADMIN_ROLE}
