openapi: 3.0.3

info:
  title: InsuraHub API
  version: 1.0.0
  description: |
    REST API for InsuraHub.

tags:
  - name: Consumers
    description: Operations related to consumer management

paths:
  /api/consumers:
    $ref: './consumer/paths.yaml#/consumers'
