openapi: 3.0.3

info:
  title: InsuraHub API
  version: 1.0.0
  description: |
    REST API for InsuraHub.

tags:
  - name: Users
    description: Operations related to user management

paths:
  /api/users:
    $ref: './user/paths.yaml#/users'
